# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#

class Event(object):

    def __init__(self, attributes, response):
        self.attributes = attributes
        self.response = response

    @property
    def action(self):
        return self.attributes.get('action')

    @property
    def created_at(self):
        return self.attributes.get('created_at')

    @property
    def details(self):
        return self.attributes.get('details')

    @property
    def id(self):
        return self.attributes.get('id')

    @property
    def links(self):
        return self.attributes.get('links')

    @property
    def metadata(self):
        return self.attributes.get('metadata')

    @property
    def resource_type(self):
        return self.attributes.get('resource_type')


# TODO: handle links properly, and double check how response is exposed

