# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#

class Export(object):
    """A thin wrapper around a export, providing easy access to its
    attributes.

    Example:
      export = client.exports.get()
      export.id
    """

    def __init__(self, attributes, api_response):
        self.attributes = attributes
        self.api_response = api_response

    @property
    def created_at(self):
        return self.attributes.get('created_at')
  

    @property
    def currency(self):
        return self.attributes.get('currency')
  

    @property
    def download_url(self):
        return self.attributes.get('download_url')
  

    @property
    def export_type(self):
        return self.attributes.get('export_type')
  

    @property
    def id(self):
        return self.attributes.get('id')
  


  

  

  

  

  

