# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#

class Mandate(object):

    def __init__(self, attributes, response):
        self.attributes = attributes
        self.response = response

    @property
    def created_at(self):
        return self.attributes.get('created_at')

    @property
    def id(self):
        return self.attributes.get('id')

    @property
    def links(self):
        return self.attributes.get('links')

    @property
    def metadata(self):
        return self.attributes.get('metadata')

    @property
    def next_possible_charge_date(self):
        return self.attributes.get('next_possible_charge_date')

    @property
    def reference(self):
        return self.attributes.get('reference')

    @property
    def scheme(self):
        return self.attributes.get('scheme')

    @property
    def status(self):
        return self.attributes.get('status')


# TODO: handle links properly, and double check how response is exposed

