# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#

class ModulusCheck(object):
    """A thin wrapper around a modulus_check, providing easy access to its
    attributes.

    Example:
      modulus_check = client.modulus_checks.get()
      modulus_check.id
    """

    def __init__(self, attributes, response):
        self.attributes = attributes
        self.response = response

    @property
    def available_schemes(self):
        return self.attributes.get('available_schemes')

    @property
    def errors(self):
        return self.attributes.get('errors')

    @property
    def succeeded(self):
        return self.attributes.get('succeeded')


# TODO: handle links properly, and double check how response is exposed

