# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#

class PaymentAccountTransaction(object):
    """A thin wrapper around a payment_account_transaction, providing easy access to its
    attributes.

    Example:
      payment_account_transaction = client.payment_account_transactions.get()
      payment_account_transaction.id
    """

    def __init__(self, attributes, api_response):
        self.attributes = attributes
        self.api_response = api_response

    @property
    def amount(self):
        return self.attributes.get('amount')
  

    @property
    def balance_after_transaction(self):
        return self.attributes.get('balance_after_transaction')
  

    @property
    def counterparty_name(self):
        return self.attributes.get('counterparty_name')
  

    @property
    def currency(self):
        return self.attributes.get('currency')
  

    @property
    def description(self):
        return self.attributes.get('description')
  

    @property
    def direction(self):
        return self.attributes.get('direction')
  

    @property
    def id(self):
        return self.attributes.get('id')
  

    @property
    def links(self):
        return self.Links(self.attributes.get('links'))
  

    @property
    def reference(self):
        return self.attributes.get('reference')
  

    @property
    def value_date(self):
        return self.attributes.get('value_date')
  


  

  

  

  

  

  

  

  
    class Links(object):
        """Wrapper for the response's 'links' attribute."""

        def __init__(self, attributes):
            self.attributes = attributes
    
        @property
        def outbound_payment(self):
            return self.attributes.get('outbound_payment')
    
        @property
        def payment_bank_account(self):
            return self.attributes.get('payment_bank_account')
    
        @property
        def payout(self):
            return self.attributes.get('payout')
    
  

  

  

