# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#

class ScenarioSimulator(object):
    """A thin wrapper around a scenario_simulator, providing easy access to its
    attributes.

    Example:
      scenario_simulator = client.scenario_simulators.get()
      scenario_simulator.id
    """

    def __init__(self, attributes, api_response):
        self.attributes = attributes
        self.api_response = api_response

    @property
    def id(self):
        return self.attributes.get('id')
  


  

