# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#

class SchemeIdentifier(object):
    """A thin wrapper around a scheme_identifier, providing easy access to its
    attributes.

    Example:
      scheme_identifier = client.scheme_identifiers.get()
      scheme_identifier.id
    """

    def __init__(self, attributes, api_response):
        self.attributes = attributes
        self.api_response = api_response

    @property
    def address_line1(self):
        return self.attributes.get('address_line1')
  

    @property
    def address_line2(self):
        return self.attributes.get('address_line2')
  

    @property
    def address_line3(self):
        return self.attributes.get('address_line3')
  

    @property
    def can_specify_mandate_reference(self):
        return self.attributes.get('can_specify_mandate_reference')
  

    @property
    def city(self):
        return self.attributes.get('city')
  

    @property
    def country_code(self):
        return self.attributes.get('country_code')
  

    @property
    def created_at(self):
        return self.attributes.get('created_at')
  

    @property
    def currency(self):
        return self.attributes.get('currency')
  

    @property
    def email(self):
        return self.attributes.get('email')
  

    @property
    def id(self):
        return self.attributes.get('id')
  

    @property
    def minimum_advance_notice(self):
        return self.attributes.get('minimum_advance_notice')
  

    @property
    def name(self):
        return self.attributes.get('name')
  

    @property
    def phone_number(self):
        return self.attributes.get('phone_number')
  

    @property
    def postal_code(self):
        return self.attributes.get('postal_code')
  

    @property
    def reference(self):
        return self.attributes.get('reference')
  

    @property
    def region(self):
        return self.attributes.get('region')
  

    @property
    def scheme(self):
        return self.attributes.get('scheme')
  

    @property
    def status(self):
        return self.attributes.get('status')
  


  

  

  

  

  

  

  

  

  

  

  

  

  

  

  

  

  

  

