# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#

class TransferredMandate(object):
    """A thin wrapper around a transferred_mandate, providing easy access to its
    attributes.

    Example:
      transferred_mandate = client.transferred_mandates.get()
      transferred_mandate.id
    """

    def __init__(self, attributes, api_response):
        self.attributes = attributes
        self.api_response = api_response

    @property
    def encrypted_customer_bank_details(self):
        return self.attributes.get('encrypted_customer_bank_details')
  

    @property
    def encrypted_decryption_key(self):
        return self.attributes.get('encrypted_decryption_key')
  

    @property
    def links(self):
        return self.Links(self.attributes.get('links'))
  

    @property
    def public_key_id(self):
        return self.attributes.get('public_key_id')
  


  

  

  
    class Links(object):
        """Wrapper for the response's 'links' attribute."""

        def __init__(self, attributes):
            self.attributes = attributes
    
        @property
        def customer_bank_account(self):
            return self.attributes.get('customer_bank_account')
    
        @property
        def mandate(self):
            return self.attributes.get('mandate')
    
  

  

