# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#

import json

import pytest
import responses

from gocardless_pro import api_client

from . import helpers

access_token = 'access-token-xyz'

@pytest.fixture
def client():
    return api_client.ApiClient('http://example.com', access_token)


def test_rate_limit_properties_are_initialized(client):
    assert client.rate_limit.limit == None
    assert client.rate_limit.remaining == None
    assert client.rate_limit.reset == None

@responses.activate
def test_rate_limit_headers_are_exposed(client):
    headers = {
      'ratelimit-limit': '1000',
      'ratelimit-remaining': '163',
      'ratelimit-reset': 'Thu, 03 May 2018 16:00:00 GMT'
    }
    responses.add(responses.GET, 'http://example.com/test', body='{}', headers=headers)

    client.get('/test')
    assert client.rate_limit.limit == 1000
    assert client.rate_limit.remaining == 163
    assert client.rate_limit.reset == 'Thu, 03 May 2018 16:00:00 GMT'

@responses.activate
def test_rate_limit_headers_are_missing(client):
    responses.add(responses.GET, 'http://example.com/test', body='{}')

    client.get('/test')
    assert client.rate_limit.limit == None
    assert client.rate_limit.remaining == None
    assert client.rate_limit.reset == None
