# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#

from . import base_service
from .. import resources

class ModulusChecksService(base_service.BaseService):
    """Service class that provides access to the modulus_checks
    endpoints of the GoCardless Pro API.
    """

    RESOURCE_CLASS = resources.ModulusCheck
    RESOURCE_NAME = 'modulus_checks'

    def create(self, params=None):
        """Perform a modulus check.

        Performs a modulus check.
        
        Bank account details may
        either be supplied using the IBAN (international bank account number),
        or [local details](#ui-compliance-local-bank-details). For more
        information on the different fields required in each country, please
        see the [local bank details](#ui-compliance-local-bank-details)
        section.

        Args:
          params (dict, optional): Request body.

        Returns:
          ModulusCheck
        """
        path = '/modulus_checks'
        response = self._perform_request('POST', path, params)
        return self._resource_for(response)

