# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#

from . import base_service
from .. import resources
from ..paginator import Paginator
from .. import errors

class PaymentAccountsService(base_service.BaseService):
    """Service class that provides access to the payment_accounts
    endpoints of the GoCardless Pro API.
    """

    RESOURCE_CLASS = resources.PaymentAccount
    RESOURCE_NAME = 'payment_accounts'


    def list(self,params=None, headers=None):
        """List payment accounts.

        Returns a [cursor-paginated](#api-usage-cursor-pagination) list of your
        payment accounts.

        Args:
              params (dict, optional): Query string parameters.

        Returns:
              ListResponse of PaymentAccount instances
        """
        path = '/payment_accounts'
        

        response = self._perform_request('GET', path, params, headers,
                                         retry_failures=True)
        return self._resource_for(response)

    def all(self,params=None):
        if params is None:
            params = {}
        return Paginator(self, params, identity_params={
          })
    
  
