# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#

from . import base_service
from .. import resources

class PayoutsService(base_service.BaseService):
    RESOURCE_CLASS = resources.Payout
    RESOURCE_NAME = 'payouts'

    def list(self, params=None):
        path = '/payouts'
        response = self._perform_request('GET', path, params)
        return self._resource_for(response)

    def get(self, identity, params=None):
        path = self._sub_url_params('/payouts/:identity', {
            'identity': identity,
        })
        response = self._perform_request('GET', path, params)
        return self._resource_for(response)

