# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#

from . import base_service
from .. import resources
from ..paginator import Paginator
from .. import errors

class TransferredMandatesService(base_service.BaseService):
    """Service class that provides access to the transferred_mandates
    endpoints of the GoCardless Pro API.
    """

    RESOURCE_CLASS = resources.TransferredMandate
    RESOURCE_NAME = 'transferred_mandates'


    def transferred_mandates(self,identity,params=None, headers=None):
        """Get updated customer bank details.

        Returns new customer bank details for a mandate that's been recently
        transferred

        Args:
              identity (string): Unique identifier, beginning with "MD". Note that this prefix may not apply to mandates created before 2016.
              params (dict, optional): Query string parameters.

        Returns:
              TransferredMandate
        """
        path = self._sub_url_params('/transferred_mandates/:identity', {
          
            'identity': identity,
          })
        
        response = self._perform_request('GET', path, params, headers,
                                         retry_failures=False)
        return self._resource_for(response)
  
