# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#

import json

import pytest
import requests
import responses

from gocardless_pro.errors import MalformedResponseError
from gocardless_pro import resources
from gocardless_pro import list_response

from .. import helpers

@responses.activate
def test_funds_availabilities_check():
    fixture = helpers.load_fixture('funds_availabilities')['check']
    helpers.stub_response(fixture)
    response = helpers.client.funds_availabilities.check(*fixture['url_params'])
    if fixture['body'].get('available') is not None and isinstance(fixture['body'].get('available'), (dict, list)):
        body = fixture['body']['available']
    else:
        body = fixture['body']

    assert isinstance(response, resources.FundsAvailability)
    assert responses.calls[-1].request.headers.get('Idempotency-Key') is None
    assert response.available == body.get('available')

def test_timeout_funds_availabilities_check_doesnt_retry():
    fixture = helpers.load_fixture('funds_availabilities')['check']
    with helpers.stub_timeout(fixture) as rsps:
      with pytest.raises(requests.ConnectTimeout):
        response = helpers.client.funds_availabilities.check(*fixture['url_params'])
      assert len(rsps.calls) == 1

def test_502_funds_availabilities_check_doesnt_retry():
    fixture = helpers.load_fixture('funds_availabilities')['check']
    with helpers.stub_502(fixture) as rsps:
      with pytest.raises(MalformedResponseError):
        response = helpers.client.funds_availabilities.check(*fixture['url_params'])
      assert len(rsps.calls) == 1
