# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#

# Code Sample Tests
# These tests verify that the documentation code samples are syntactically valid
# and can execute against a mocked API without errors.
#
# IMPORTANT: These tests do NOT verify business logic - they only verify that
# the code samples compile and execute without syntax errors.

import re
import sys
from io import StringIO

import responses

import gocardless_pro






@responses.activate
def test_billing_requests_create_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/billing_requests'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'billing_requests': {} }
    for _ in range(5):
        responses.add(
            'POST',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.billing_requests.create(params={
          "payment_request": {
            "description": "First Payment",
            "amount": "500",
            "currency": "GBP",
          },
          "mandate_request": {
            "scheme": "bacs"
          }
        })
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_billing_requests_collect_customer_details_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/billing_requests/:identity/actions/collect_customer_details'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'billing_requests': {} }
    for _ in range(5):
        responses.add(
            'POST',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.billing_requests.collect_customer_details("BR123", params={
          "customer": {
            "email": "alice@example.com",
            "given_name": "Alice",
            "family_name": "Smith"
          },
          "customer_billing_detail": {
            "address_line1": "1 Somewhere Lane"
          }
        })
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_billing_requests_collect_bank_account_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/billing_requests/:identity/actions/collect_bank_account'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'billing_requests': {} }
    for _ in range(5):
        responses.add(
            'POST',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.billing_requests.collect_bank_account("BR123", params={
          "account_number": "55779911",
          "branch_code": "200000",
          "account_holder_name": "Frank Osborne",
          "country_code": "GB"
        })
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_billing_requests_confirm_payer_details_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/billing_requests/:identity/actions/confirm_payer_details'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'billing_requests': {} }
    for _ in range(5):
        responses.add(
            'POST',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.billing_requests.confirm_payer_details("BR123")
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_billing_requests_fulfil_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/billing_requests/:identity/actions/fulfil'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'billing_requests': {} }
    for _ in range(5):
        responses.add(
            'POST',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.billing_requests.fulfil("BR123")
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_billing_requests_cancel_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/billing_requests/:identity/actions/cancel'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'billing_requests': {} }
    for _ in range(5):
        responses.add(
            'POST',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.billing_requests.cancel("BR123")
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_billing_requests_list_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/billing_requests'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'billing_requests': [{}], 'meta': { 'cursors': {'after': None, 'before': None}, 'limit': 50 } }
    for _ in range(5):
        responses.add(
            'GET',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.billing_requests.list().records
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_billing_requests_get_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/billing_requests/:identity'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'billing_requests': {} }
    for _ in range(5):
        responses.add(
            'GET',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.billing_requests.get("BR123")
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_billing_requests_notify_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/billing_requests/:identity/actions/notify'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'billing_requests': {} }
    for _ in range(5):
        responses.add(
            'POST',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.billing_requests.notify("BR123", params={
          "notification_type": "email",
          "redirect_uri": "https://my-company.com"
        })
    finally:
        sys.stdout = old_stdout











