# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#

# Code Sample Tests
# These tests verify that the documentation code samples are syntactically valid
# and can execute against a mocked API without errors.
#
# IMPORTANT: These tests do NOT verify business logic - they only verify that
# the code samples compile and execute without syntax errors.

import re
import sys
from io import StringIO

import responses

import gocardless_pro






@responses.activate
def test_blocks_create_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/blocks'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'blocks': {} }
    for _ in range(5):
        responses.add(
            'POST',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        block = client.blocks.create(
          params={
            "block_type": "email",
            "reason_type": "no_intent_to_pay",
            "resource_reference": "example@example.com"
          }
        )
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_blocks_get_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/blocks/:identity'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'blocks': {} }
    for _ in range(5):
        responses.add(
            'GET',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        block = client.blocks.get("BLC456")
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_blocks_list_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/blocks'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'blocks': [{}], 'meta': { 'cursors': {'after': None, 'before': None}, 'limit': 50 } }
    for _ in range(5):
        responses.add(
            'GET',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        for block in client.blocks.all():
          print(block.id)
          print(block.block_type)
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_blocks_disable_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/blocks/:identity/actions/disable'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'blocks': {} }
    for _ in range(5):
        responses.add(
            'POST',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        block = client.blocks.disable("BLC123")
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_blocks_enable_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/blocks/:identity/actions/enable'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'blocks': {} }
    for _ in range(5):
        responses.add(
            'POST',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        block = client.blocks.enable("BLC123")
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_blocks_block_by_ref_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/blocks/block_by_ref'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'blocks': [{}], 'meta': { 'cursors': {'after': None, 'before': None}, 'limit': 50 } }
    for _ in range(5):
        responses.add(
            'POST',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        response = client.blocks.block_by_ref(
          params={
            "reference_type": "customer",
            "reference_value": "CU123",
            "reason_type": "no_intent_to_pay"
          }
        )
        blocks = response.records
    finally:
        sys.stdout = old_stdout


