# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#

# Code Sample Tests
# These tests verify that the documentation code samples are syntactically valid
# and can execute against a mocked API without errors.
#
# IMPORTANT: These tests do NOT verify business logic - they only verify that
# the code samples compile and execute without syntax errors.

import re
import sys
from io import StringIO

import responses

import gocardless_pro






@responses.activate
def test_customer_notifications_handle_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/customer_notifications/:identity/actions/handle'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'customer_notifications': {} }
    for _ in range(5):
        responses.add(
            'POST',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.customer_notifications.handle("PCN123")
    finally:
        sys.stdout = old_stdout


