# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#

# Code Sample Tests
# These tests verify that the documentation code samples are syntactically valid
# and can execute against a mocked API without errors.
#
# IMPORTANT: These tests do NOT verify business logic - they only verify that
# the code samples compile and execute without syntax errors.

import re
import sys
from io import StringIO

import responses

import gocardless_pro






@responses.activate
def test_customers_create_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/customers'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'customers': {} }
    for _ in range(5):
        responses.add(
            'POST',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.customers.create(params={
          "email": "user@example.com",
          "given_name": "Frank",
          "family_name": "Osborne",
          "address_line1": "27 Acer Road",
          "address_line2": "Apt 2",
          "city": "London",
          "postal_code": "E8 3GX",
          "country_code": "GB",
          "metadata": {
            "salesforce_id": "ABCD1234"
          }
        })
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_customers_list_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/customers'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'customers': [{}], 'meta': { 'cursors': {'after': None, 'before': None}, 'limit': 50 } }
    for _ in range(5):
        responses.add(
            'GET',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.customers.list().records

        client.customers.list(params={"after": "CU123"}).records
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_customers_get_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/customers/:identity'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'customers': {} }
    for _ in range(5):
        responses.add(
            'GET',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.customers.get("CU123")
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_customers_update_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/customers/:identity'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'customers': {} }
    for _ in range(5):
        responses.add(
            'PUT',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.customers.update("CU123", params={
          "email": "updated_user@example.com"
        })
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_customers_remove_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/customers/:identity'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'customers': {} }
    for _ in range(5):
        responses.add(
            'DELETE',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.customers.remove("CU123")
    finally:
        sys.stdout = old_stdout


