# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#

# Code Sample Tests
# These tests verify that the documentation code samples are syntactically valid
# and can execute against a mocked API without errors.
#
# IMPORTANT: These tests do NOT verify business logic - they only verify that
# the code samples compile and execute without syntax errors.

import re
import sys
from io import StringIO

import responses

import gocardless_pro






@responses.activate
def test_mandates_create_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/mandates'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'mandates': {} }
    for _ in range(5):
        responses.add(
            'POST',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.mandates.create(params={
          "scheme": "bacs",
          "metadata": {
            "contract": "ABCD1234"
           },
          "links": {
            "customer_bank_account": "BA123",
            "creditor": "CR123"
          }
        })
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_mandates_list_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/mandates'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'mandates': [{}], 'meta': { 'cursors': {'after': None, 'before': None}, 'limit': 50 } }
    for _ in range(5):
        responses.add(
            'GET',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.mandates.list().records

        client.mandates.list(params={"customer": "CU123"}).records
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_mandates_get_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/mandates/:identity'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'mandates': {} }
    for _ in range(5):
        responses.add(
            'GET',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.mandates.get("MD123")
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_mandates_update_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/mandates/:identity'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'mandates': {} }
    for _ in range(5):
        responses.add(
            'PUT',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.mandates.update("MD123", params={
          "metadata": {"key": "value"}
        })
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_mandates_cancel_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/mandates/:identity/actions/cancel'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'mandates': {} }
    for _ in range(5):
        responses.add(
            'POST',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.mandates.cancel("MD123")
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_mandates_reinstate_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/mandates/:identity/actions/reinstate'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'mandates': {} }
    for _ in range(5):
        responses.add(
            'POST',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.mandates.reinstate("MD123")
    finally:
        sys.stdout = old_stdout


