# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#

# Code Sample Tests
# These tests verify that the documentation code samples are syntactically valid
# and can execute against a mocked API without errors.
#
# IMPORTANT: These tests do NOT verify business logic - they only verify that
# the code samples compile and execute without syntax errors.

import re
import sys
from io import StringIO

import responses

import gocardless_pro






@responses.activate
def test_payer_authorisations_get_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/payer_authorisations/:identity'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'payer_authorisations': {} }
    for _ in range(5):
        responses.add(
            'GET',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.payer_authorisations.get("PAU123")
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_payer_authorisations_create_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/payer_authorisations'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'payer_authorisations': {} }
    for _ in range(5):
        responses.add(
            'POST',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.payer_authorisations.create(params={
            "customer": {
              "email": "mail@example.com",
              "given_name": "Name",
              "family_name": "Surname",
              "metadata": {}
            },
            "bank_account": {
              "account_holder_name": "Name Surname",
              "branch_code": "200000",
              "account_number": "55779911",
              "metadata": {}
            },
            "mandate": {
              "reference": "XYZ789",
              "metadata": {}
            }
        })
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_payer_authorisations_update_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/payer_authorisations/:identity'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'payer_authorisations': {} }
    for _ in range(5):
        responses.add(
            'PUT',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.payer_authorisations.update("PA123", params={
            "customer": {
              "email": "mail@example.com",
              "given_name": "Name",
              "family_name": "Surname",
              "metadata": {
                "salesforce_id": "EFGH5678"
              }
            },
            "bank_account": {
              "account_holder_name": "Name Surname",
              "branch_code": "200000",
              "account_number": "55779911",
            },
            "mandate": {
              "reference": "XYZ789",
            }
        })
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_payer_authorisations_submit_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/payer_authorisations/:identity/actions/submit'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'payer_authorisations': {} }
    for _ in range(5):
        responses.add(
            'POST',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.payer_authorisations.submit("PAU123")
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_payer_authorisations_confirm_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/payer_authorisations/:identity/actions/confirm'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'payer_authorisations': {} }
    for _ in range(5):
        responses.add(
            'POST',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.payer_authorisations.confirm("PAU123")
    finally:
        sys.stdout = old_stdout


