# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#

# Code Sample Tests
# These tests verify that the documentation code samples are syntactically valid
# and can execute against a mocked API without errors.
#
# IMPORTANT: These tests do NOT verify business logic - they only verify that
# the code samples compile and execute without syntax errors.

import re
import sys
from io import StringIO

import responses

import gocardless_pro






@responses.activate
def test_payments_create_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/payments'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'payments': {} }
    for _ in range(5):
        responses.add(
            'POST',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.payments.create(params={
          "amount": 100,
          "currency": "GBP",
          "charge_date": "2014-05-19",
          "reference": "WINEBOX001",
          "metadata": {
            "order_dispatch_date": "2014-05-22"
          },
          "links": {
            "mandate": "MD123"
          }
        })
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_payments_list_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/payments'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'payments': [{}], 'meta': { 'cursors': {'after': None, 'before': None}, 'limit': 50 } }
    for _ in range(5):
        responses.add(
            'GET',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.payments.list().records

        client.payments.list(params={"customer": "CU123"}).records
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_payments_get_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/payments/:identity'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'payments': {} }
    for _ in range(5):
        responses.add(
            'GET',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.payments.get("PM123")
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_payments_update_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/payments/:identity'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'payments': {} }
    for _ in range(5):
        responses.add(
            'PUT',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.payments.update("PM123", params={
          "metadata": {"key": "value"}
        })
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_payments_cancel_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/payments/:identity/actions/cancel'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'payments': {} }
    for _ in range(5):
        responses.add(
            'POST',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.payments.cancel("PM123")
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_payments_retry_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/payments/:identity/actions/retry'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'payments': {} }
    for _ in range(5):
        responses.add(
            'POST',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.payments.retry("PM123")
    finally:
        sys.stdout = old_stdout


