# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#

# Code Sample Tests
# These tests verify that the documentation code samples are syntactically valid
# and can execute against a mocked API without errors.
#
# IMPORTANT: These tests do NOT verify business logic - they only verify that
# the code samples compile and execute without syntax errors.

import re
import sys
from io import StringIO

import responses

import gocardless_pro






@responses.activate
def test_webhooks_list_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/webhooks'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'webhooks': [{}], 'meta': { 'cursors': {'after': None, 'before': None}, 'limit': 50 } }
    for _ in range(5):
        responses.add(
            'GET',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.webhooks.list().records

        client.webhooks.list(params={"successful": True}).records
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_webhooks_get_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/webhooks/:identity'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'webhooks': {} }
    for _ in range(5):
        responses.add(
            'GET',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.webhooks.get("WB123")
    finally:
        sys.stdout = old_stdout




@responses.activate
def test_webhooks_retry_code_sample():
    # Convert :param placeholders to regex wildcards for flexible matching
    stub_url = '/webhooks/:identity/actions/retry'
    url_pattern = re.compile('https://api.gocardless.com' + re.sub(r':[\w]+', r'[^/]+', stub_url))
    # Mock response - repeat multiple times to handle code samples with multiple API calls
    response_body = { 'webhooks': {} }
    for _ in range(5):
        responses.add(
            'POST',
            url_pattern,
            json=response_body,
            status=200
        )

    client = gocardless_pro.Client(access_token='SECRET_TOKEN', environment='live')

    # Suppress stdout from code samples that use print
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        client.webhooks.retry("WB123")
    finally:
        sys.stdout = old_stdout


