# WARNING: Do not edit by hand, this file was generated by Crank:
#
#   https://github.com/gocardless/crank
#

class ListResponse(object):

    def __init__(self, resources, response):
        self.resources = resources
        self.response = response

    def __iter__(self):
        return iter(self.resources)

    @property
    def before(self):
        return self.response.json()['meta']['cursors']['before']

    @property
    def after(self):
        return self.response.json()['meta']['cursors']['after']
